### ISSUE TITLE
is it possible to show this themes in Rmarkdown html code chunk ?

### ISSUE THREAD

**Issue by TonyFly3000** [jnolis/synthwave85#5]
Hi , It look cool. I want to share it in the Rmarkdown html code chunk with this themes .

Is it  possible ?

**Comment by jnolis** [comment]
You could do that, but it would be a fair amount of work. The theme itself is css, and Rmarkdown supports css for code chunks. So you would take the [theme file](https://github.com/jnolis/synthwave85/blob/master/Synthwave85.rstheme), and change the names of the different classes to match the code chunks, then create a new style sheet to load into the Rmarkdown ([see here](https://bookdown.org/yihui/rmarkdown/language-engines.html#javascript-and-css)).

If you do get this working I'd love to see it!
